repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        language_version: python3.8
        args: ["--line-length=120"]
        stages: [commit]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--line-length=120"]
        stages: [commit]

# Temporarily disable flake8 and mypy for deployment
#-   repo: https://github.com/pycqa/flake8
#    rev: 5.0.4
#    hooks:
#    -   id: flake8

#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.7.1
#    hooks:
#    -   id: mypy
#        args: [--ignore-missing-imports, --no-strict-optional]
#        additional_dependencies:
#        -   types-requests
#        -   types-Flask
#        -   types-Jinja2
#        -   types-Werkzeug
#        -   types-PyYAML
#        -   types-PyMySQL
#        -   types-cryptography

# Add a pre-push hook to run tests
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        stages: [push]
        types: [python]
