-- Grant necessary permissions to the meetingspot user
GRANT ALL PRIVILEGES ON DATABASE findameetingspot TO meetingspot;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO meetingspot;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO meetingspot;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO meetingspot;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO meetingspot;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO meetingspot;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO meetingspot;
