env_variables:
  ENCRYPTION_KEY: ${sm://projects/find-a-meeting-spot/secrets/encryption-key/latest}
  JWT_SECRET_KEY: ${sm://projects/find-a-meeting-spot/secrets/jwt-secret-key/latest}
  GOOGLE_MAPS_API_KEY: ${sm://projects/find-a-meeting-spot/secrets/google-maps-api-key/latest}
  MAILGUN_API_KEY: ${sm://projects/find-a-meeting-spot/secrets/mailgun-api-key/latest}
  MAILGUN_DOMAIN: ${sm://projects/find-a-meeting-spot/secrets/mailgun-domain/latest} 