"""add_selected_place_id_column

Revision ID: 2019042e1033
Revises: 715ddd7ea1ee
Create Date: 2025-04-14 12:50:07.219934

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.models.types import UUIDType

# revision identifiers, used by Alembic.
revision = "2019042e1033"
down_revision = "715ddd7ea1ee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add selected_place_id column to meeting_requests table
    # This is needed because a previous migration failed to apply properly
    op.add_column("meeting_requests", sa.Column("selected_place_id", UUIDType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the selected_place_id column
    op.drop_column("meeting_requests", "selected_place_id")
    # ### end Alembic commands ###
