"""Make password_hash nullable for OAuth users

Revision ID: 5c9553c5fdc8
Revises: 9b430c7496d6
Create Date: 2025-04-09 11:09:07.665681

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5c9553c5fdc8"
down_revision = "9b430c7496d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("password_hash", existing_type=sa.VARCHAR(length=128), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("password_hash", existing_type=sa.VARCHAR(length=128), nullable=False)

    # ### end Alembic commands ###
