"""Add ON DELETE CASCADE to foreign keys

Revision ID: 84151472c340
Revises: 12aab2f7036a
Create Date: 2025-04-15 10:49:43.454360

"""
import uuid

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.dialects.postgresql import UUID as pgUUID

# Import UUIDType directly instead of app.models.types
from sqlalchemy.types import CHAR, TypeDecorator


class UUIDType(TypeDecorator):
    """Platform-independent GUID type.
    Uses PostgreSQL's UUID type, otherwise uses
    CHAR(36), storing as stringified hex values.
    """

    impl = CHAR
    cache_ok = True

    def load_dialect_impl(self, dialect):
        if dialect.name == "postgresql":
            return dialect.type_descriptor(pgUUID())
        else:
            return dialect.type_descriptor(CHAR(36))

    def process_bind_param(self, value, dialect):
        if value is None:
            return value
        elif dialect.name == "postgresql":
            return str(value)
        else:
            if not isinstance(value, uuid.UUID):
                return str(uuid.UUID(value))
            else:
                return str(value)

    def process_result_value(self, value, dialect):
        if value is None:
            return value
        else:
            if not isinstance(value, uuid.UUID):
                value = uuid.UUID(value)
            return value


# Define a JSONType replacement
class JSONType(TypeDecorator):
    impl = sa.Text

    def process_bind_param(self, value, dialect):
        import json

        if value is None:
            return None
        return json.dumps(value)

    def process_result_value(self, value, dialect):
        import json

        if value is None:
            return None
        return json.loads(value)


# revision identifiers, used by Alembic.
revision = "84151472c340"
down_revision = "12aab2f7036a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("id", UUIDType(length=36), nullable=False),
        sa.Column("user_id", UUIDType(length=36), nullable=False),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=True),
        sa.Column("plan_id", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_subscription_id"),
    )
    op.create_table(
        "meeting_contacts",
        sa.Column("meeting_request_id", UUIDType(length=36), nullable=True),
        sa.Column("contact_id", UUIDType(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["meeting_request_id"], ["meeting_requests.request_id"], ondelete="CASCADE"),
    )
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column("email", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("phone", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("company", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("notes", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"], ondelete="CASCADE")
        batch_op.drop_column("last_interaction")
        batch_op.drop_column("contact_email")
        batch_op.drop_column("nickname")

    with op.batch_alter_table("meeting_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_b_email", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("user_b_name", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("location_a", JSONType(), nullable=False))
        batch_op.add_column(sa.Column("location_b", JSONType(), nullable=True))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "users", ["user_a_id"], ["id"], ondelete="CASCADE")

    with op.batch_alter_table("places", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "users", ["suggested_by_id"], ["id"], ondelete="CASCADE")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash", existing_type=sa.VARCHAR(length=128), type_=sa.String(length=256), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash", existing_type=sa.String(length=256), type_=sa.VARCHAR(length=128), nullable=False
        )

    with op.batch_alter_table("places", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "users", ["suggested_by_id"], ["id"])

    with op.batch_alter_table("meeting_requests", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "users", ["user_a_id"], ["id"])
        batch_op.drop_column("location_b")
        batch_op.drop_column("location_a")
        batch_op.drop_column("user_b_name")
        batch_op.drop_column("user_b_email")

    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("nickname", sa.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column("contact_email", sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column("last_interaction", sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])
        batch_op.drop_column("updated_at")
        batch_op.drop_column("notes")
        batch_op.drop_column("company")
        batch_op.drop_column("phone")
        batch_op.drop_column("email")
        batch_op.drop_column("name")

    op.drop_table("meeting_contacts")
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
