name: Backend CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Google Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        
      - name: Configure Docker
        run: gcloud auth configure-docker
        
      - name: Build and Push Backend Container
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/meeting-spot-backend:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/meeting-spot-backend:${{ github.sha }}
          
      - name: Deploy Backend to Cloud Run
        run: |
          gcloud run deploy meeting-spot-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/meeting-spot-backend:${{ github.sha }} \
            --platform managed \
            --region us-east1 \
            --allow-unauthenticated \
            --set-env-vars="FLASK_ENV=production"
